# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e107c199400d37f7eabe494c6b44c676260de9a53715bfbd3b64ad7658cf699733255ae46a4ef689b06452e001d32e3714600d81cce9a12e66313ed8b7aa575

test:
  secret_key_base: 8440488d00646de6aafe5e747f938e11f2f71ba1c2ad9a2f2a5c9518503b417488ac9d0f6970bc2ed4965efea5b07fc011c9ac6b18dbfd41404ec8eaf3a7ffcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
